/*
    Example API call: https://garuda.stg.linkedin.com/drill_down#site:lva1
*/
export const getEnvironmentDataAPIResponse = {
  getEnvironmentData: {
    dcrs: [
      {
        Hostname: "lva1-dcr01.nw.linkedin.com",
        Asn: 64515,
        Site: "lva1",
        Environment: null,
        DeviceClass: "dcr",
        Cluster: null,
        Pod: null,
      },
      {
        Hostname: "lva1-dcr02.nw.linkedin.com",
        Asn: 64515,
        Site: "lva1",
        Environment: null,
        DeviceClass: "dcr",
        Cluster: null,
        Pod: null,
      },
      {
        Hostname: "lva1-dcr03.nw.linkedin.com",
        Asn: 64515,
        Site: "lva1",
        Environment: null,
        DeviceClass: "dcr",
        Cluster: null,
        Pod: null,
      },
      {
        Hostname: "lva1-dcr04.nw.linkedin.com",
        Asn: 64515,
        Site: "lva1",
        Environment: null,
        DeviceClass: "dcr",
        Cluster: null,
        Pod: null,
      },
    ],
    rfabs: [
      {
        Hostname: "lva1-p-a-rfab01.nw.linkedin.com",
        Asn: 4220020001,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "a",
      },
      {
        Hostname: "lva1-p-a-rfab02.nw.linkedin.com",
        Asn: 4220020001,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "a",
      },
      {
        Hostname: "lva1-p-a-rfab03.nw.linkedin.com",
        Asn: 4220020001,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "a",
      },
      {
        Hostname: "lva1-p-a-rfab04.nw.linkedin.com",
        Asn: 4220020001,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "a",
      },
      {
        Hostname: "lva1-p-a-rfab05.nw.linkedin.com",
        Asn: 4220020001,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "a",
      },
      {
        Hostname: "lva1-p-a-rfab06.nw.linkedin.com",
        Asn: 4220020001,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "a",
      },
      {
        Hostname: "lva1-p-a-rfab07.nw.linkedin.com",
        Asn: 4220020001,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "a",
      },
      {
        Hostname: "lva1-p-a-rfab08.nw.linkedin.com",
        Asn: 4220020001,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "a",
      },
      {
        Hostname: "lva1-p-b-rfab01.nw.linkedin.com",
        Asn: 4220020033,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "b",
      },
      {
        Hostname: "lva1-p-b-rfab02.nw.linkedin.com",
        Asn: 4220020033,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "b",
      },
      {
        Hostname: "lva1-p-b-rfab03.nw.linkedin.com",
        Asn: 4220020033,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "b",
      },
      {
        Hostname: "lva1-p-b-rfab04.nw.linkedin.com",
        Asn: 4220020033,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "b",
      },
      {
        Hostname: "lva1-p-b-rfab05.nw.linkedin.com",
        Asn: 4220020033,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "b",
      },
      {
        Hostname: "lva1-p-b-rfab06.nw.linkedin.com",
        Asn: 4220020033,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "b",
      },
      {
        Hostname: "lva1-p-b-rfab07.nw.linkedin.com",
        Asn: 4220020033,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "b",
      },
      {
        Hostname: "lva1-p-b-rfab08.nw.linkedin.com",
        Asn: 4220020033,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "b",
      },
      {
        Hostname: "lva1-p-c-rfab01.nw.linkedin.com",
        Asn: 4220020065,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "c",
      },
      {
        Hostname: "lva1-p-c-rfab02.nw.linkedin.com",
        Asn: 4220020065,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "c",
      },
      {
        Hostname: "lva1-p-c-rfab03.nw.linkedin.com",
        Asn: 4220020065,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "c",
      },
      {
        Hostname: "lva1-p-c-rfab04.nw.linkedin.com",
        Asn: 4220020065,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "c",
      },
      {
        Hostname: "lva1-p-c-rfab05.nw.linkedin.com",
        Asn: 4220020065,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "c",
      },
      {
        Hostname: "lva1-p-c-rfab06.nw.linkedin.com",
        Asn: 4220020065,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "c",
      },
      {
        Hostname: "lva1-p-c-rfab07.nw.linkedin.com",
        Asn: 4220020065,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "c",
      },
      {
        Hostname: "lva1-p-c-rfab08.nw.linkedin.com",
        Asn: 4220020065,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "c",
      },
      {
        Hostname: "lva1-p-d-rfab01.nw.linkedin.com",
        Asn: 4220020097,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "d",
      },
      {
        Hostname: "lva1-p-d-rfab02.nw.linkedin.com",
        Asn: 4220020097,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "d",
      },
      {
        Hostname: "lva1-p-d-rfab03.nw.linkedin.com",
        Asn: 4220020097,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "d",
      },
      {
        Hostname: "lva1-p-d-rfab04.nw.linkedin.com",
        Asn: 4220020097,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "d",
      },
      {
        Hostname: "lva1-p-d-rfab05.nw.linkedin.com",
        Asn: 4220020097,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "d",
      },
      {
        Hostname: "lva1-p-d-rfab06.nw.linkedin.com",
        Asn: 4220020097,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "d",
      },
      {
        Hostname: "lva1-p-d-rfab07.nw.linkedin.com",
        Asn: 4220020097,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "d",
      },
      {
        Hostname: "lva1-p-d-rfab08.nw.linkedin.com",
        Asn: 4220020097,
        Site: "lva1",
        Environment: "p",
        DeviceClass: "rfab",
        Cluster: "p",
        Pod: null,
        Plane: "d",
      },
    ],
    clusters: ["p", "pb", "pc"],
    dcrClusterLinks: null,
    rfabClusterLinks: [
      { source: "lva1-p-a-rfab01.nw.linkedin.com", target: "p" },
      { source: "lva1-p-a-rfab01.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-a-rfab01.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-a-rfab02.nw.linkedin.com", target: "p" },
      { source: "lva1-p-a-rfab02.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-a-rfab02.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-a-rfab03.nw.linkedin.com", target: "p" },
      { source: "lva1-p-a-rfab03.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-a-rfab03.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-a-rfab04.nw.linkedin.com", target: "p" },
      { source: "lva1-p-a-rfab04.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-a-rfab04.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-a-rfab05.nw.linkedin.com", target: "p" },
      { source: "lva1-p-a-rfab05.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-a-rfab05.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-a-rfab06.nw.linkedin.com", target: "p" },
      { source: "lva1-p-a-rfab06.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-a-rfab06.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-a-rfab07.nw.linkedin.com", target: "p" },
      { source: "lva1-p-a-rfab07.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-a-rfab07.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-a-rfab08.nw.linkedin.com", target: "p" },
      { source: "lva1-p-a-rfab08.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-a-rfab08.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-b-rfab01.nw.linkedin.com", target: "p" },
      { source: "lva1-p-b-rfab01.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-b-rfab01.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-b-rfab02.nw.linkedin.com", target: "p" },
      { source: "lva1-p-b-rfab02.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-b-rfab02.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-b-rfab03.nw.linkedin.com", target: "p" },
      { source: "lva1-p-b-rfab03.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-b-rfab03.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-b-rfab04.nw.linkedin.com", target: "p" },
      { source: "lva1-p-b-rfab04.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-b-rfab04.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-b-rfab05.nw.linkedin.com", target: "p" },
      { source: "lva1-p-b-rfab05.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-b-rfab05.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-b-rfab06.nw.linkedin.com", target: "p" },
      { source: "lva1-p-b-rfab06.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-b-rfab06.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-b-rfab07.nw.linkedin.com", target: "p" },
      { source: "lva1-p-b-rfab07.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-b-rfab07.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-b-rfab08.nw.linkedin.com", target: "p" },
      { source: "lva1-p-b-rfab08.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-b-rfab08.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-c-rfab01.nw.linkedin.com", target: "p" },
      { source: "lva1-p-c-rfab01.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-c-rfab01.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-c-rfab02.nw.linkedin.com", target: "p" },
      { source: "lva1-p-c-rfab02.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-c-rfab02.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-c-rfab03.nw.linkedin.com", target: "p" },
      { source: "lva1-p-c-rfab03.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-c-rfab03.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-c-rfab04.nw.linkedin.com", target: "p" },
      { source: "lva1-p-c-rfab04.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-c-rfab04.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-c-rfab05.nw.linkedin.com", target: "p" },
      { source: "lva1-p-c-rfab05.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-c-rfab05.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-c-rfab06.nw.linkedin.com", target: "p" },
      { source: "lva1-p-c-rfab06.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-c-rfab06.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-c-rfab07.nw.linkedin.com", target: "p" },
      { source: "lva1-p-c-rfab07.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-c-rfab07.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-c-rfab08.nw.linkedin.com", target: "p" },
      { source: "lva1-p-c-rfab08.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-c-rfab08.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-d-rfab01.nw.linkedin.com", target: "p" },
      { source: "lva1-p-d-rfab01.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-d-rfab01.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-d-rfab02.nw.linkedin.com", target: "p" },
      { source: "lva1-p-d-rfab02.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-d-rfab02.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-d-rfab03.nw.linkedin.com", target: "p" },
      { source: "lva1-p-d-rfab03.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-d-rfab03.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-d-rfab04.nw.linkedin.com", target: "p" },
      { source: "lva1-p-d-rfab04.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-d-rfab04.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-d-rfab05.nw.linkedin.com", target: "p" },
      { source: "lva1-p-d-rfab05.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-d-rfab05.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-d-rfab06.nw.linkedin.com", target: "p" },
      { source: "lva1-p-d-rfab06.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-d-rfab06.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-d-rfab07.nw.linkedin.com", target: "p" },
      { source: "lva1-p-d-rfab07.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-d-rfab07.nw.linkedin.com", target: "pc" },
      { source: "lva1-p-d-rfab08.nw.linkedin.com", target: "p" },
      { source: "lva1-p-d-rfab08.nw.linkedin.com", target: "pb" },
      { source: "lva1-p-d-rfab08.nw.linkedin.com", target: "pc" },
    ],
    dcrRfabLinks: [
      {
        source: "lva1-dcr01.nw.linkedin.com",
        target: "lva1-p-a-rfab01.nw.linkedin.com",
      },
      {
        source: "lva1-dcr01.nw.linkedin.com",
        target: "lva1-p-a-rfab05.nw.linkedin.com",
      },
      {
        source: "lva1-dcr01.nw.linkedin.com",
        target: "lva1-p-b-rfab01.nw.linkedin.com",
      },
      {
        source: "lva1-dcr01.nw.linkedin.com",
        target: "lva1-p-b-rfab05.nw.linkedin.com",
      },
      {
        source: "lva1-dcr01.nw.linkedin.com",
        target: "lva1-p-c-rfab01.nw.linkedin.com",
      },
      {
        source: "lva1-dcr01.nw.linkedin.com",
        target: "lva1-p-c-rfab05.nw.linkedin.com",
      },
      {
        source: "lva1-dcr01.nw.linkedin.com",
        target: "lva1-p-d-rfab01.nw.linkedin.com",
      },
      {
        source: "lva1-dcr01.nw.linkedin.com",
        target: "lva1-p-d-rfab05.nw.linkedin.com",
      },
      {
        source: "lva1-dcr02.nw.linkedin.com",
        target: "lva1-p-a-rfab02.nw.linkedin.com",
      },
      {
        source: "lva1-dcr02.nw.linkedin.com",
        target: "lva1-p-a-rfab06.nw.linkedin.com",
      },
      {
        source: "lva1-dcr02.nw.linkedin.com",
        target: "lva1-p-b-rfab02.nw.linkedin.com",
      },
      {
        source: "lva1-dcr02.nw.linkedin.com",
        target: "lva1-p-b-rfab06.nw.linkedin.com",
      },
      {
        source: "lva1-dcr02.nw.linkedin.com",
        target: "lva1-p-c-rfab02.nw.linkedin.com",
      },
      {
        source: "lva1-dcr02.nw.linkedin.com",
        target: "lva1-p-c-rfab06.nw.linkedin.com",
      },
      {
        source: "lva1-dcr02.nw.linkedin.com",
        target: "lva1-p-d-rfab02.nw.linkedin.com",
      },
      {
        source: "lva1-dcr02.nw.linkedin.com",
        target: "lva1-p-d-rfab06.nw.linkedin.com",
      },
      {
        source: "lva1-dcr03.nw.linkedin.com",
        target: "lva1-p-a-rfab03.nw.linkedin.com",
      },
      {
        source: "lva1-dcr03.nw.linkedin.com",
        target: "lva1-p-a-rfab07.nw.linkedin.com",
      },
      {
        source: "lva1-dcr03.nw.linkedin.com",
        target: "lva1-p-b-rfab03.nw.linkedin.com",
      },
      {
        source: "lva1-dcr03.nw.linkedin.com",
        target: "lva1-p-b-rfab07.nw.linkedin.com",
      },
      {
        source: "lva1-dcr03.nw.linkedin.com",
        target: "lva1-p-c-rfab03.nw.linkedin.com",
      },
      {
        source: "lva1-dcr03.nw.linkedin.com",
        target: "lva1-p-c-rfab07.nw.linkedin.com",
      },
      {
        source: "lva1-dcr03.nw.linkedin.com",
        target: "lva1-p-d-rfab03.nw.linkedin.com",
      },
      {
        source: "lva1-dcr03.nw.linkedin.com",
        target: "lva1-p-d-rfab07.nw.linkedin.com",
      },
      {
        source: "lva1-dcr04.nw.linkedin.com",
        target: "lva1-p-a-rfab04.nw.linkedin.com",
      },
      {
        source: "lva1-dcr04.nw.linkedin.com",
        target: "lva1-p-a-rfab08.nw.linkedin.com",
      },
      {
        source: "lva1-dcr04.nw.linkedin.com",
        target: "lva1-p-b-rfab04.nw.linkedin.com",
      },
      {
        source: "lva1-dcr04.nw.linkedin.com",
        target: "lva1-p-b-rfab08.nw.linkedin.com",
      },
      {
        source: "lva1-dcr04.nw.linkedin.com",
        target: "lva1-p-c-rfab04.nw.linkedin.com",
      },
      {
        source: "lva1-dcr04.nw.linkedin.com",
        target: "lva1-p-c-rfab08.nw.linkedin.com",
      },
      {
        source: "lva1-dcr04.nw.linkedin.com",
        target: "lva1-p-d-rfab04.nw.linkedin.com",
      },
      {
        source: "lva1-dcr04.nw.linkedin.com",
        target: "lva1-p-d-rfab08.nw.linkedin.com",
      },
    ],
  },
};
