export const getFabsDataAPIResponse = {
  getFabsData: [
    {
      fab: {
        Hostname: "lor1-x-b-fab01.nw.linkedin.com",
        Asn: 64907,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: [
        {
          Hostname: "lor1-dcr01.nw.linkedin.com",
          Asn: 64529,
          Site: "lor1",
          Environment: null,
          DeviceClass: "dcr",
          Cluster: null,
          Pod: null,
        },
      ],
      rfabs: null,
      pods: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "50",
        "51",
        "52",
        "53",
        "54",
        "55",
        "56",
        "57",
        "58",
        "59",
        "60",
      ],
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab02.nw.linkedin.com",
        Asn: 64908,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: [
        {
          Hostname: "lor1-dcr02.nw.linkedin.com",
          Asn: 64529,
          Site: "lor1",
          Environment: null,
          DeviceClass: "dcr",
          Cluster: null,
          Pod: null,
        },
      ],
      rfabs: null,
      pods: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "50",
        "51",
        "52",
        "53",
        "54",
        "55",
        "56",
        "57",
        "58",
        "59",
        "60",
      ],
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab03.nw.linkedin.com",
        Asn: 64909,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: [
        {
          Hostname: "lor1-dcr03.nw.linkedin.com",
          Asn: 64529,
          Site: "lor1",
          Environment: null,
          DeviceClass: "dcr",
          Cluster: null,
          Pod: null,
        },
      ],
      rfabs: null,
      pods: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "50",
        "51",
        "52",
        "53",
        "54",
        "55",
        "56",
        "57",
        "58",
        "59",
        "60",
      ],
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab04.nw.linkedin.com",
        Asn: 64910,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: [
        {
          Hostname: "lor1-dcr04.nw.linkedin.com",
          Asn: 64529,
          Site: "lor1",
          Environment: null,
          DeviceClass: "dcr",
          Cluster: null,
          Pod: null,
        },
      ],
      rfabs: null,
      pods: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "50",
        "51",
        "52",
        "53",
        "54",
        "55",
        "56",
        "57",
        "58",
        "59",
        "60",
      ],
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab05.nw.linkedin.com",
        Asn: 64911,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: [
        {
          Hostname: "lor1-dcr01.nw.linkedin.com",
          Asn: 64529,
          Site: "lor1",
          Environment: null,
          DeviceClass: "dcr",
          Cluster: null,
          Pod: null,
        },
      ],
      rfabs: null,
      pods: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "50",
        "51",
        "52",
        "53",
        "54",
        "55",
        "56",
        "57",
        "58",
        "59",
        "60",
      ],
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab06.nw.linkedin.com",
        Asn: 64912,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: [
        {
          Hostname: "lor1-dcr02.nw.linkedin.com",
          Asn: 64529,
          Site: "lor1",
          Environment: null,
          DeviceClass: "dcr",
          Cluster: null,
          Pod: null,
        },
      ],
      rfabs: null,
      pods: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "50",
        "51",
        "52",
        "53",
        "54",
        "55",
        "56",
        "57",
        "58",
        "59",
        "60",
      ],
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab07.nw.linkedin.com",
        Asn: 64913,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: [
        {
          Hostname: "lor1-dcr03.nw.linkedin.com",
          Asn: 64529,
          Site: "lor1",
          Environment: null,
          DeviceClass: "dcr",
          Cluster: null,
          Pod: null,
        },
      ],
      rfabs: null,
      pods: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "50",
        "51",
        "52",
        "53",
        "54",
        "55",
        "56",
        "57",
        "58",
        "59",
        "60",
      ],
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab08.nw.linkedin.com",
        Asn: 64914,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: [
        {
          Hostname: "lor1-dcr04.nw.linkedin.com",
          Asn: 64529,
          Site: "lor1",
          Environment: null,
          DeviceClass: "dcr",
          Cluster: null,
          Pod: null,
        },
      ],
      rfabs: null,
      pods: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "50",
        "51",
        "52",
        "53",
        "54",
        "55",
        "56",
        "57",
        "58",
        "59",
        "60",
      ],
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab09.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: [
        {
          Hostname: "lor1-dcr01.nw.linkedin.com",
          Asn: 64529,
          Site: "lor1",
          Environment: null,
          DeviceClass: "dcr",
          Cluster: null,
          Pod: null,
        },
      ],
      rfabs: null,
      pods: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "50",
        "51",
        "52",
        "53",
        "54",
        "55",
        "56",
        "57",
        "58",
        "59",
        "60",
        "62",
        "63",
        "65",
        "66",
        "67",
        "68",
        "69",
        "70",
        "71",
        "72",
        "73",
        "74",
        "75",
        "76",
        "77",
        "78",
        "79",
        "80",
        "81",
        "82",
        "83",
        "84",
        "85",
        "86",
        "87",
        "88",
        "89",
        "90",
        "91",
        "92",
        "93",
        "94",
        "95",
        "96",
      ],
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab10.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: [
        {
          Hostname: "lor1-dcr02.nw.linkedin.com",
          Asn: 64529,
          Site: "lor1",
          Environment: null,
          DeviceClass: "dcr",
          Cluster: null,
          Pod: null,
        },
      ],
      rfabs: null,
      pods: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "50",
        "51",
        "52",
        "53",
        "54",
        "55",
        "56",
        "57",
        "58",
        "59",
        "60",
        "62",
        "63",
        "65",
        "66",
        "67",
        "68",
        "69",
        "70",
        "71",
        "72",
        "73",
        "74",
        "75",
        "76",
        "77",
        "78",
        "79",
        "80",
        "81",
        "82",
        "83",
        "84",
        "85",
        "86",
        "87",
        "88",
        "89",
        "90",
        "91",
        "92",
        "93",
        "94",
        "95",
        "96",
      ],
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab11.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: [
        {
          Hostname: "lor1-dcr03.nw.linkedin.com",
          Asn: 64529,
          Site: "lor1",
          Environment: null,
          DeviceClass: "dcr",
          Cluster: null,
          Pod: null,
        },
      ],
      rfabs: null,
      pods: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "50",
        "51",
        "52",
        "53",
        "54",
        "55",
        "56",
        "57",
        "58",
        "59",
        "60",
        "62",
        "63",
        "65",
        "66",
        "67",
        "68",
        "69",
        "70",
        "71",
        "72",
        "73",
        "74",
        "75",
        "76",
        "77",
        "78",
        "79",
        "80",
        "81",
        "82",
        "83",
        "84",
        "85",
        "86",
        "87",
        "88",
        "89",
        "90",
        "91",
        "92",
        "93",
        "94",
        "95",
        "96",
      ],
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab12.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: [
        {
          Hostname: "lor1-dcr04.nw.linkedin.com",
          Asn: 64529,
          Site: "lor1",
          Environment: null,
          DeviceClass: "dcr",
          Cluster: null,
          Pod: null,
        },
      ],
      rfabs: null,
      pods: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "50",
        "51",
        "52",
        "53",
        "54",
        "55",
        "56",
        "57",
        "58",
        "59",
        "60",
        "62",
        "63",
        "65",
        "66",
        "67",
        "68",
        "69",
        "70",
        "71",
        "72",
        "73",
        "74",
        "75",
        "76",
        "77",
        "78",
        "79",
        "80",
        "81",
        "82",
        "83",
        "84",
        "85",
        "86",
        "87",
        "88",
        "89",
        "90",
        "91",
        "92",
        "93",
        "94",
        "95",
        "96",
      ],
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab13.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: [
        {
          Hostname: "lor1-dcr01.nw.linkedin.com",
          Asn: 64529,
          Site: "lor1",
          Environment: null,
          DeviceClass: "dcr",
          Cluster: null,
          Pod: null,
        },
      ],
      rfabs: null,
      pods: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "50",
        "51",
        "52",
        "53",
        "54",
        "55",
        "56",
        "57",
        "58",
        "59",
        "60",
        "62",
        "63",
        "65",
        "66",
        "67",
        "68",
        "69",
        "70",
        "71",
        "72",
        "73",
        "74",
        "75",
        "76",
        "77",
        "78",
        "79",
        "80",
        "81",
        "82",
        "83",
        "84",
        "85",
        "86",
        "87",
        "88",
        "89",
        "90",
        "91",
        "92",
        "93",
        "94",
        "95",
        "96",
      ],
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab14.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: [
        {
          Hostname: "lor1-dcr02.nw.linkedin.com",
          Asn: 64529,
          Site: "lor1",
          Environment: null,
          DeviceClass: "dcr",
          Cluster: null,
          Pod: null,
        },
      ],
      rfabs: null,
      pods: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "50",
        "51",
        "52",
        "53",
        "54",
        "55",
        "56",
        "57",
        "58",
        "59",
        "60",
        "62",
        "63",
        "65",
        "66",
        "67",
        "68",
        "69",
        "70",
        "71",
        "72",
        "73",
        "74",
        "75",
        "76",
        "77",
        "78",
        "79",
        "80",
        "81",
        "82",
        "83",
        "84",
        "85",
        "86",
        "87",
        "88",
        "89",
        "90",
        "91",
        "92",
        "93",
        "94",
        "95",
        "96",
      ],
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab15.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: [
        {
          Hostname: "lor1-dcr03.nw.linkedin.com",
          Asn: 64529,
          Site: "lor1",
          Environment: null,
          DeviceClass: "dcr",
          Cluster: null,
          Pod: null,
        },
      ],
      rfabs: null,
      pods: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "50",
        "51",
        "52",
        "53",
        "54",
        "55",
        "56",
        "57",
        "58",
        "59",
        "60",
        "62",
        "63",
        "65",
        "66",
        "67",
        "68",
        "69",
        "70",
        "71",
        "72",
        "73",
        "74",
        "75",
        "76",
        "77",
        "78",
        "79",
        "80",
        "81",
        "82",
        "83",
        "84",
        "85",
        "86",
        "87",
        "88",
        "89",
        "90",
        "91",
        "92",
        "93",
        "94",
        "95",
        "96",
      ],
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab16.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: [
        {
          Hostname: "lor1-dcr04.nw.linkedin.com",
          Asn: 64529,
          Site: "lor1",
          Environment: null,
          DeviceClass: "dcr",
          Cluster: null,
          Pod: null,
        },
      ],
      rfabs: null,
      pods: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "50",
        "51",
        "52",
        "53",
        "54",
        "55",
        "56",
        "57",
        "58",
        "59",
        "60",
        "62",
        "63",
        "65",
        "66",
        "67",
        "68",
        "69",
        "70",
        "71",
        "72",
        "73",
        "74",
        "75",
        "76",
        "77",
        "78",
        "79",
        "80",
        "81",
        "82",
        "83",
        "84",
        "85",
        "86",
        "87",
        "88",
        "89",
        "90",
        "91",
        "92",
        "93",
        "94",
        "95",
        "96",
      ],
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab17.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: null,
      rfabs: null,
      pods: null,
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab18.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: null,
      rfabs: null,
      pods: null,
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab19.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: null,
      rfabs: null,
      pods: null,
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab20.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: null,
      rfabs: null,
      pods: null,
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab21.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: null,
      rfabs: null,
      pods: null,
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab22.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: null,
      rfabs: null,
      pods: null,
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab23.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: null,
      rfabs: null,
      pods: null,
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab24.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: null,
      rfabs: null,
      pods: null,
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab25.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: null,
      rfabs: null,
      pods: null,
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab26.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: null,
      rfabs: null,
      pods: null,
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab27.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: null,
      rfabs: null,
      pods: null,
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab28.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: null,
      rfabs: null,
      pods: null,
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab29.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: null,
      rfabs: null,
      pods: null,
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab30.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: null,
      rfabs: null,
      pods: null,
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab31.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: null,
      rfabs: null,
      pods: null,
    },
    {
      fab: {
        Hostname: "lor1-x-b-fab32.nw.linkedin.com",
        Asn: 4220320417,
        Site: "lor1",
        Environment: "x",
        DeviceClass: "fab",
        Cluster: "x",
        Pod: null,
      },
      dcrs: null,
      rfabs: null,
      pods: null,
    },
  ],
};
